---

trigger:
- master 

pool:
  name: Default
  demands:
    - agent.name -equals devops-agent

variables:
  name: Yash

jobs:
- job: 
  displayName: 'Run one-line script'
  steps:
  - script: |
      echo Hello, $(name)..!
      ls -l
      pwd
      echo $(Build.sourcesdirectory)

- job: Build
  displayName: 'Build and Push container Image'
  steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'acrtestregistry12' #service connection name
      imageRepository: 'acr-service-connection'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)' 